language: node_js
node_js:
- '5'
notifications:
  slack:
    secure: lmbur9oCgqNhIjay38sef8xYyAE+M2dk7INqFHoGkd613nHQb8aDIMUrM6ho6jURrHYePTPYgx9CU3XRGPY0xJMgry+QqYTN/bgZG53ajgn2fLL+eJBlKni0a6ylkF1NC88FCUmLDLC2PNHaYsRNUJKygiE4gghydBrpL1dZK8ac6+Vs+NZlBmfs12vT/4wBvGOHqkGNAzC9mbliL7a3O/jL5r/GRS0vr/XNdSCZm1tPlDZY81DHuvKScupygcgwSj3Zqm1f4vCwk4nzxBKXK1gg70FPN1zFEdCr1Nz2XWJl4uFQNG3c6EuqjgTDcY40zwp/9MAaVaLsmvKifnHIZIEziiyZESNH8bdt/0RgeQww0rbiCmqEsvjUKNkCqR9RMtNiTFz42Y5wuMTsNHQ3CYNR2dccBOaahrkOolVHE4maausaSFkvQSwZP4uelKwCtHUAN/gQk+CiyA1QABX78cid+C1vuGfk4cFGZnd5Z7ZeMSkDzNW5RFMAIYZSwqbzJx2oso5WEcnZFNLNMIvcvba9hnrc26n0v0RmXeE4MPZDcf01hJF+itoLuq4UfqT9WTarD5tiTIv6Oj7udKQ9AUMACtK/YkMLCaow17qU0nEJPbDqyzgk3koGuuuGFhC89GiL5shrWZHYIiWg+icBVbcxF6S5jJFPQ/qjIMkho7w=
  email: false
